language: python
python:
  - "2.7"
install:
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
before_script:
  - psql -c 'create extension hstore;' -U postgres
  - psql -c 'create database folivora;' -U postgres
script: ./manage.py test folivora
