language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coverage
before_script:
  - psql -c 'create extension hstore;' -U postgres template1
  - psql -c 'create database folivora;' -U postgres
script: coverage run ./manage.py test folivora && coverage report
